source 'https://rubygems.org'

gem 'chefspec', '~> 3.4'
gem 'rspec', '= 2.14'
gem 'rspec-core', '= 2.14'
gem 'rspec-expectations', '= 2.14'
gem 'rspec-mocks', '= 2.14'
gem 'chef', '~> 11.8'
gem 'foodcritic', '~> 3.0.0'
gem 'daptiv-foodcritic-rules'
gem 'rubocop'
gem 'rake'
gem 'berkshelf', '~> 3.2.3'
gem 'minitest-chef-handler'
gem 'daptiv-chef-ci', '~> 0.0.13'
gem 'json', '~> 1.7.7'
gem 'rest-client', '~> 1.6.8'

group :development do
  gem 'test-kitchen', '~> 1.0'
  gem 'kitchen-vagrant', '~> 0.11'
  gem 'guard'
  gem 'guard-kitchen'
  gem 'busser'
  gem 'busser-minitest'
end
