name             'netscaler'
maintainer       'Daptiv Solutions, LLC'
maintainer_email 'cpc_sea_teamengineering@changepoint.com'
license          'All rights reserved'
description      'A collection of resources for managing Citrix NetScaler'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.5'
issues_url 'https://github.com/daptiv/netscaler/issues'
source_url 'https://github.com/daptiv/netscaler/'
supports 'ubuntu'
supports 'amazon'
supports 'debian'
supports 'windows'
